[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#7d4166'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#401a31'

# Color used for almost all text
textColor = '#e0b8d1'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "serif"